version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependabot"
      - "github-actions"
    commit-message:
      prefix: "chore"
    groups:
      github-actions-updates:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependabot"
      - "docker"
    commit-message:
      prefix: "chore"
    groups:
      docker-updates:
        patterns:
          - "*"
