name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug!"
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Flutter version
      description: What version of Flutter Docker image are you using?
    validations:
      required: true
